CREATE TABLE IF NOT EXISTS news_settings (
  id TINYINT NOT NULL PRIMARY KEY,
  push_enabled TINYINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO news_settings (id, push_enabled) VALUES (1, 1);
